<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lupa password</name>
   <tag></tag>
   <elementGuidId>3093dbb9-aa51-4ec8-8570-1b49cd17d4bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiStack-root.mui-style-1avhoj5 > a.MuiTypography-root.MuiTypography-subtitle2.MuiLink-root.MuiLink-underlineHover.mui-style-1rat08z</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/div/form/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f5752576-007f-46f3-ab3b-bf027598b82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-subtitle2 MuiLink-root MuiLink-underlineHover mui-style-1rat08z</value>
      <webElementGuid>a06aced5-a50c-4791-a011-4a8908de5990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/auth/reset-password</value>
      <webElementGuid>a864058d-954a-4109-9e42-a62b271a1e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lupa password?</value>
      <webElementGuid>2184fa88-599f-41df-8333-8b13902cea0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root mui-style-0&quot;]/div[@class=&quot;mui-style-v82cpl&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthSm mui-style-1m6pqln&quot;]/div[@class=&quot;mui-style-18yadix&quot;]/form[1]/div[@class=&quot;MuiStack-root mui-style-1avhoj5&quot;]/a[@class=&quot;MuiTypography-root MuiTypography-subtitle2 MuiLink-root MuiLink-underlineHover mui-style-1rat08z&quot;]</value>
      <webElementGuid>b365d176-248f-44ed-9d0e-f93304b39c82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/form/div[2]/a</value>
      <webElementGuid>6927402a-9f5b-4c16-93f9-f3ec25b09cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lupa password?')]</value>
      <webElementGuid>347392c7-1913-4bb5-b81a-00e733c34191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/auth/reset-password')]</value>
      <webElementGuid>890799dc-d6c5-4f79-bd06-d31415b0eb4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>083c1e89-10cd-4744-aa77-efb26835e04c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/auth/reset-password' and (text() = 'Lupa password?' or . = 'Lupa password?')]</value>
      <webElementGuid>5fe0e5d3-9b33-4368-8204-0a0aa1ba0a33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
