<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Download QR Code</name>
   <tag></tag>
   <elementGuidId>ad6d7121-3242-46c4-aa5a-d9892a2137ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4decdc4f-0d0b-48be-81bb-ae4a1fde8f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a6ae34cb-2782-4af4-8b5f-ded86ef46293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-center text-base font-semibold h-10 rounded px-4 border transition outline-none !text-white bg-secondary text-secondary border-secondary hover:brightness-110 hover:!bg-secondary focus:brightness-110 focus:ring-2 ring-secondary w-64</value>
      <webElementGuid>6d266c21-316b-4ea8-a6d0-2f1d934cf3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>download-qr-code</value>
      <webElementGuid>e3e9db50-687c-4a66-ba7c-170468c530f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download QR Code</value>
      <webElementGuid>db02a9a6-639e-43ae-8920-a2ec0dd0537c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;min-h-screen flex items-stretch text-base text-xen-gray-900&quot;]/div[@class=&quot;flex-1 lg:px-8 xl:px-8 lg:py-8 min-h-screen&quot;]/div[@class=&quot;w-full h-full mx-auto lg:max-w-2xl flex flex-col&quot;]/div[@class=&quot;flex-1&quot;]/section[@class=&quot;pt-8 pb-12 px-4 lg:px-0 max-w-screen-sm mx-auto&quot;]/div[@class=&quot;flex flex-col items-center space-y-8 py-8&quot;]/div[@class=&quot;hidden md:flex flex-col space-y-2&quot;]/button[@class=&quot;flex items-center justify-center text-base font-semibold h-10 rounded px-4 border transition outline-none !text-white bg-secondary text-secondary border-secondary hover:brightness-110 hover:!bg-secondary focus:brightness-110 focus:ring-2 ring-secondary w-64&quot;]</value>
      <webElementGuid>cc1604ca-ae5b-415c-887a-b772d8f8a1d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>95676aaf-76be-44b0-a513-ed75ee1027c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/section/div/div[2]/button</value>
      <webElementGuid>800b66ed-99f9-45e6-9ff5-ec4f163859c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[2]/button</value>
      <webElementGuid>f5300655-e657-419a-8edb-2b995d78249d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Download QR Code' or . = 'Download QR Code')]</value>
      <webElementGuid>826aa633-9a9f-429f-842e-946501eb5575</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
