<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Back</name>
   <tag></tag>
   <elementGuidId>a273f361-c048-4cf2-bab4-498b7972d551</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e42b0b9e-d763-45cf-befd-a247e5a71e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8e675cc6-e6df-4a66-96ab-f386a1dd6a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-center text-base font-semibold h-10 rounded px-4 border transition outline-none border-2 hover:text-white focus:ring-2 !bg-transparent bg-secondary text-secondary border-secondary hover:brightness-110 hover:!bg-secondary focus:brightness-110 focus:ring-2 ring-secondary w-64</value>
      <webElementGuid>fb369768-cd27-41ae-a680-b055782a6b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>back</value>
      <webElementGuid>86d2c232-2c31-480f-8683-45e274269bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back</value>
      <webElementGuid>9c887518-0702-4f53-91d7-e499834902d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;min-h-screen flex items-stretch text-base text-xen-gray-900&quot;]/div[@class=&quot;flex-1 lg:px-8 xl:px-8 lg:py-8 min-h-screen&quot;]/div[@class=&quot;w-full h-full mx-auto lg:max-w-2xl flex flex-col&quot;]/div[@class=&quot;flex-1&quot;]/section[@class=&quot;pt-8 pb-12 px-4 lg:px-0 max-w-screen-sm mx-auto&quot;]/div[@class=&quot;flex flex-col items-center space-y-8 py-8&quot;]/div[@class=&quot;hidden md:flex flex-col space-y-2&quot;]/button[@class=&quot;flex items-center justify-center text-base font-semibold h-10 rounded px-4 border transition outline-none border-2 hover:text-white focus:ring-2 !bg-transparent bg-secondary text-secondary border-secondary hover:brightness-110 hover:!bg-secondary focus:brightness-110 focus:ring-2 ring-secondary w-64&quot;]</value>
      <webElementGuid>151ed533-d064-48db-afdf-a7849c46de66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>0d3ec355-8559-476b-ae67-554eac54c080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/section/div/div[2]/button[2]</value>
      <webElementGuid>8686bd18-fe52-487a-95d4-bd2c6c9624ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>95b4a520-35a5-4366-98fa-f25a4893aeff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Back' or . = 'Back')]</value>
      <webElementGuid>1bccbe2e-f33e-45ab-9154-ff04a3b3bc93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
