<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Download QR Code</name>
   <tag></tag>
   <elementGuidId>371f60a5-7c1d-4a41-9d83-950a42f9b733</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>733e43db-1a7f-4c9c-a94d-05105aa330a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0b3db9a7-a18b-43d8-8a43-7dc3141dcc87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-center text-base font-semibold h-10 rounded px-4 border transition outline-none !text-white bg-secondary text-secondary border-secondary hover:brightness-110 hover:!bg-secondary focus:brightness-110 focus:ring-2 ring-secondary w-64</value>
      <webElementGuid>63126fe1-ab73-4343-9c5c-bed5a0642d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>download-qr-code</value>
      <webElementGuid>d4a7d2c0-220e-4dca-96ae-b73428eabc23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download QR Code</value>
      <webElementGuid>64ee38e3-1d58-47dc-9030-a609b3b0fb91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;min-h-screen flex items-stretch text-base text-xen-gray-900&quot;]/div[@class=&quot;flex-1 lg:px-8 xl:px-8 lg:py-8 min-h-screen&quot;]/div[@class=&quot;w-full h-full mx-auto lg:max-w-2xl flex flex-col&quot;]/div[@class=&quot;flex-1&quot;]/section[@class=&quot;pt-8 pb-12 px-4 lg:px-0 max-w-screen-sm mx-auto&quot;]/div[@class=&quot;flex flex-col items-center space-y-8 py-8&quot;]/div[@class=&quot;hidden md:flex flex-col space-y-2&quot;]/button[@class=&quot;flex items-center justify-center text-base font-semibold h-10 rounded px-4 border transition outline-none !text-white bg-secondary text-secondary border-secondary hover:brightness-110 hover:!bg-secondary focus:brightness-110 focus:ring-2 ring-secondary w-64&quot;]</value>
      <webElementGuid>37155d0d-a7b9-4e80-8984-912c164327b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>b9ab5d9c-82e0-4e9a-84b8-8944ace77e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/section/div/div[2]/button</value>
      <webElementGuid>cbf5996d-9b5d-4da2-83c1-667c4761215c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[2]/button</value>
      <webElementGuid>68fdacc1-09e9-4a02-9f54-26279abb55e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Download QR Code' or . = 'Download QR Code')]</value>
      <webElementGuid>dacccafd-69bd-4399-bd60-7b37d2966068</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
