<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar Sekarang</name>
   <tag></tag>
   <elementGuidId>5aa298bb-da7b-4086-8426-8714157d20b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div[2]/div/div/div[2]/div/div[4]/div/div/div/div[3]/div/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>07a45c7b-5a85-4e1f-9df7-23d499296eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium mui-style-2nlxd2</value>
      <webElementGuid>1478e53d-2922-49ec-adaf-38d59815c9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>16ebda67-8ffe-4a29-ade2-accefd2fcdb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/payment/review/rjFNQbtuQg4pDXhAbpmI</value>
      <webElementGuid>874b5027-78c2-4cd4-9a07-d3c34d629efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Sekarang</value>
      <webElementGuid>9e22f844-a90c-4da6-82ae-2c742a5df899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiStack-root mui-style-o44is&quot;]/div[@class=&quot;MuiBox-root mui-style-j1fy4m&quot;]/div[@class=&quot;MuiBox-root mui-style-0&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg mui-style-rcalj5&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg mui-style-1qsxih2&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-6 mui-style-sayu3r&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-lg-9 mui-style-1hjwhii&quot;]/div[@class=&quot;MuiStack-root mui-style-1orv6po&quot;]/div[4]/div[1]/div[@class=&quot;MuiBox-root mui-style-ohwg9z&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container mui-style-k8kfiq&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-1 mui-style-bi6uus&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation0 MuiCard-root mui-style-1jdslth&quot;]/div[@class=&quot;MuiCardContent-root mui-style-970mk2&quot;]/div[@class=&quot;MuiStack-root mui-style-1q73y56&quot;]/div[@class=&quot;MuiStack-root mui-style-1ov46kg&quot;]/a[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium mui-style-2nlxd2&quot;]</value>
      <webElementGuid>f4a770fe-7048-4f4d-8bc6-4cc914b3ed49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[2]/div/div/div[2]/div/div[4]/div/div/div/div[3]/div/div/div/div[2]/a</value>
      <webElementGuid>ac74523f-9eee-4eb8-b139-f64bd7110a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Daftar Sekarang')])[3]</value>
      <webElementGuid>b71a4c96-716c-4980-8517-0997d83515ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/payment/review/rjFNQbtuQg4pDXhAbpmI')]</value>
      <webElementGuid>3eeabeaa-8c33-4f0d-871a-48721bf60143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/a</value>
      <webElementGuid>95c706a8-7531-4555-8e09-66b9b033da95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/payment/review/rjFNQbtuQg4pDXhAbpmI' and (text() = 'Daftar Sekarang' or . = 'Daftar Sekarang')]</value>
      <webElementGuid>c003e92b-11f1-4ebd-9c5a-aa9173a21083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[2]/div/div/div[2]/div/div[4]/div/div/div/div[2]/div/div/div/div[2]/a</value>
      <webElementGuid>b7674d14-25c2-46ee-90dd-7bc1604c3118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Daftar Sekarang')])[2]</value>
      <webElementGuid>f028de04-30dc-46c3-9b60-0948582653b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/payment/review/UPzP4kfS4b67u7xPK79m')]</value>
      <webElementGuid>bd82f738-fdaf-4340-9b31-98c846e05b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/a</value>
      <webElementGuid>0d345805-9909-4ad5-b138-c46a3c1fc6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/payment/review/UPzP4kfS4b67u7xPK79m' and (text() = 'Daftar Sekarang' or . = 'Daftar Sekarang')]</value>
      <webElementGuid>5c43e810-426d-44a2-8e29-62a81c75fe57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[2]/div/div/div[2]/div/div[4]/div/div/div/div/div/div/div/div[2]/a</value>
      <webElementGuid>d01dcc9b-3cb0-4c68-958b-b1a1785bed11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Daftar Sekarang')]</value>
      <webElementGuid>86bf074b-cadb-44e5-811f-0f90c4d46afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/payment/review/zjfiN2nTtFXwqiQknP6z')]</value>
      <webElementGuid>ce344113-b39a-4c2c-9ed2-b36c3c1015cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/a</value>
      <webElementGuid>de0c42ac-6201-4a50-b1d3-6d4098b684e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/payment/review/zjfiN2nTtFXwqiQknP6z' and (text() = 'Daftar Sekarang' or . = 'Daftar Sekarang')]</value>
      <webElementGuid>81bb3c72-155e-48bf-9395-8005616f8ec0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
