<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_WhatsApp</name>
   <tag></tag>
   <elementGuidId>7cf96452-aeed-40ea-83ee-54689ac62ade</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.MuiButtonBase-root.MuiFab-root.MuiFab-extended.MuiFab-sizeLarge.MuiFab-primary.MuiFab-root.MuiFab-extended.MuiFab-sizeLarge.MuiFab-primary.mui-style-wwuugz</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6963a7dc-98da-41d3-839f-962d4c48c0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiFab-root MuiFab-extended MuiFab-sizeLarge MuiFab-primary MuiFab-root MuiFab-extended MuiFab-sizeLarge MuiFab-primary mui-style-wwuugz</value>
      <webElementGuid>4b7063c4-1aef-45cc-ac75-c01797a07ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a6fe0517-14ac-4934-aab1-b425ca882970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://api.whatsapp.com/send/?phone=6281212891393&amp;text=Halo+MySkill%2C+saya+mau+tanya+</value>
      <webElementGuid>a8d6065e-5fa1-4528-933d-87691ac6bece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>209a1757-c2b2-4a52-abfd-c82ec2b35a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow noopener noreferrer</value>
      <webElementGuid>7d130e7e-edd5-419c-8081-3f25c1231630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WhatsApp</value>
      <webElementGuid>2fa5e434-080f-40c3-888c-c403aac948ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiStack-root mui-style-o44is&quot;]/div[@class=&quot;MuiBox-root mui-style-1ltz7b3&quot;]/a[@class=&quot;MuiButtonBase-root MuiFab-root MuiFab-extended MuiFab-sizeLarge MuiFab-primary MuiFab-root MuiFab-extended MuiFab-sizeLarge MuiFab-primary mui-style-wwuugz&quot;]</value>
      <webElementGuid>a91c9bcd-af50-4cfb-8cb1-01ec49d851fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[5]/a</value>
      <webElementGuid>f798183c-5e29-48cb-bb22-d38131e2a96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'WhatsApp')]</value>
      <webElementGuid>fdab9f9f-9358-4bda-b076-d67f12b05eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://api.whatsapp.com/send/?phone=6281212891393&amp;text=Halo+MySkill%2C+saya+mau+tanya+')]</value>
      <webElementGuid>034c61fb-d923-4bfe-a3c5-f143e5ab8ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>eb1a3346-965f-4408-a2aa-964c833ac12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://api.whatsapp.com/send/?phone=6281212891393&amp;text=Halo+MySkill%2C+saya+mau+tanya+' and (text() = 'WhatsApp' or . = 'WhatsApp')]</value>
      <webElementGuid>d37a07ce-06a4-4304-9b68-864e1fc1d681</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
