<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Download QR Code</name>
   <tag></tag>
   <elementGuidId>04d06e14-8792-4f52-9b58-855d537b1d19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ce047bc-0023-44f1-8298-7fd2daf4fb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e2d8c5f5-1352-4467-b733-26f0568dc025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-center text-base font-semibold h-10 rounded px-4 border transition outline-none !text-white bg-secondary text-secondary border-secondary hover:brightness-110 hover:!bg-secondary focus:brightness-110 focus:ring-2 ring-secondary w-64</value>
      <webElementGuid>008476c5-b7f5-4e78-b551-7e02526550e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>download-qr-code</value>
      <webElementGuid>a92f9c02-a738-4c0b-89aa-a2eae62cd2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download QR Code</value>
      <webElementGuid>665764db-c950-4ad0-8f46-cdf5ea8cf856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;min-h-screen flex items-stretch text-base text-xen-gray-900&quot;]/div[@class=&quot;flex-1 lg:px-8 xl:px-8 lg:py-8 min-h-screen&quot;]/div[@class=&quot;w-full h-full mx-auto lg:max-w-2xl flex flex-col&quot;]/div[@class=&quot;flex-1&quot;]/section[@class=&quot;pt-8 pb-12 px-4 lg:px-0 max-w-screen-sm mx-auto&quot;]/div[@class=&quot;flex flex-col items-center space-y-8 py-8&quot;]/div[@class=&quot;hidden md:flex flex-col space-y-2&quot;]/button[@class=&quot;flex items-center justify-center text-base font-semibold h-10 rounded px-4 border transition outline-none !text-white bg-secondary text-secondary border-secondary hover:brightness-110 hover:!bg-secondary focus:brightness-110 focus:ring-2 ring-secondary w-64&quot;]</value>
      <webElementGuid>a6d93d03-3424-44be-a884-4dd7b699fdd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>f4441fdd-5390-430a-a368-de202bf9f2fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/section/div/div[2]/button</value>
      <webElementGuid>2f65fb7e-048c-4611-b897-64a7132b690e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[2]/button</value>
      <webElementGuid>5dda5f7d-7e69-434a-8e23-176e9d63d7e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Download QR Code' or . = 'Download QR Code')]</value>
      <webElementGuid>2d621d5c-c93a-4967-9088-feedcbadbbc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
